apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  serviceName: stateful
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: mongo:latest
          name: mongo
          volumeMounts:
            - name: pv-gp2-claim #needs to match with metadata-name of volumeClaimTemplates
              mountPath: /data
  volumeClaimTemplates: #this is persistent volume claim.
    - metadata:
        name: pv-gp2-claim #this is ganna be a .yaml name of pod!
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: gp2